# Generated by Django 3.1.2 on 2021-05-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=7, verbose_name='Цена'),
        ),
    ]
