# Generated by Django 3.1.2 on 2021-05-26 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'объявление', 'verbose_name_plural': 'объявления'},
        ),
    ]
