# Generated by Django 3.2.3 on 2021-05-25 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'verbose_name': 'значение температуры', 'verbose_name_plural': 'значения температур'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'имя прожект', 'verbose_name_plural': 'много имен прожект'},
        ),
    ]
