# Generated by Django 3.2.3 on 2021-05-25 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_auto_20210525_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'объект', 'verbose_name_plural': 'объекты'},
        ),
    ]
